### ISSUE TITLE
Error when trying to install firmware update: “Failed to perform the action update/install. PhynFirwmwareUpdateEntity.async_install() takes 1 positional argument but 3 were given”

### ISSUE THREAD

**Issue by irace** [jordanruthe/homeassistant-phyn#29]
> Failed to perform the action update/install. PhynFirwmwareUpdateEntity.async_install() takes 1 positional argument but 3 were given

<img width="510" alt="image" src="https://github.com/user-attachments/assets/a5ec2bc0-c5e2-4149-a015-0bb1d609e195">

Please advise, thank you!

**Comment by Hedda** [comment]
@irace Which exact GitHub repository URL did you use when installing? Can you confirm that you are using jordanruthe's repo?

https://github.com/jordanruthe/homeassistant-phyn

The reason I ask is that until recently the URL in README.md instructions was wrong and instead pointed to MizterB's repo with his original integration instead of jordanruthe's updated fork which contains fixes and features that are not (yet) in the upstream:

https://github.com/jordanruthe/homeassistant-phyn/blob/main/README.md

Regardless it would be a good idea if you could confirm which exact GitHub repository URL your installation was done from.

**Comment by irace** [comment]
Yeah I believe so!

When I open the repository from the HACS plugin overflow menu, I get https://github.com/jordanruthe/homeassistant-phyn

**Comment by irace** [comment]
Hi! Trying again here as I'm still getting the same issue:

Here's the update prompt:

<img width="599" height="392" alt="Image" src="https://github.com/user-attachments/assets/4a49496d-8e4a-472b-b483-fcb2eb70b2f3" />

Here's the error:
> Failed to perform the action update/install. PhynFirwmwareUpdateEntity.async_install() takes 1 positional argument but 3 were given

Here's what my install looks like:

<img width="1024" height="1081" alt="Image" src="https://github.com/user-attachments/assets/ca65797f-7f1e-45b5-a04e-5cb201a2807f" />

Thanks so much for your help!

**Comment by elylv** [comment]
I see a pull request was done for this, but no release.  Is the code in a state to do a release @jordanruthe ?

**Comment by jordanruthe** [comment]
This seemed not worth the effort with how quickly phyn auto updates. I've removed the alert flagging in HA. The only real case I've seen recently is for PW1 sensors where the battery is low, but as soon as the battery is fixed it auto updates.

**Comment by irace** [comment]
Hi!

A bit confused here.

I still get this error when I try to update:
> Failed to perform the action update/install. PhynFirwmwareUpdateEntity.async_install() takes 1 positional argument but 3 were given

Any advice would be really appreciated!
